# -*- coding: utf-8 -*-
# DO NOT EDIT THIS FILE
# Natron PyPlug
# This file was automatically generated by Natron PyPlug exporter version 10.

# Hand-written code should be added in a separate file named LetterAnimationExt.py
# See http://natron.readthedocs.org/en/master/devel/groups.html#adding-hand-written-code-callbacks-etc
# Note that Viewers are never exported

import NatronEngine
import sys

# Try to import the extensions file where callbacks and hand-written code should be located.
try:
    from LetterAnimationExt import *
except ImportError:
    pass

def getPluginID():
    return "vv.LetterAnimation"

def getLabel():
    return "LetterAnimation"

def getVersion():
    return 1

def getIconPath():
    return "Text.png"

def getGrouping():
    return "videovina/Texts"

def createInstance(app,group):
    # Create all nodes in the group

    # Create the parameters of the group node the same way we did for all internal nodes
    lastNode = group
    lastNode.setColor(0.7, 0.7, 0.7)
    param = lastNode.getParam("onParamChanged")
    if param is not None:
        param.setValue("letter_animation.main")
        del param


    # Create the user parameters
    lastNode.control = lastNode.createPageParam("control", "Control")
    param = lastNode.createStringParam("state_label", "State")
    param.setType(NatronEngine.StringParam.TypeEnum.eStringTypeLabel)
    param.setDefaultValue("- - - - - - - >    STATE :")
    param.restoreDefaultValue()

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setEvaluateOnChange(False)
    param.setAnimationEnabled(False)
    lastNode.state_label = param
    del param

    param = lastNode.createChoiceParam("format", "Format")
    entries = [ ("Quarter HD - 480 x 270", ""),
    ("Half HD - 960 x 540", ""),
    ("Full HD - 1920 x 1080", ""),
    ("4K - 3840 x 2160", "")]
    param.setOptions(entries)
    del entries
    param.setDefaultValue("Full HD - 1920 x 1080")
    param.restoreDefaultValue()

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.format = param
    del param

    param = lastNode.createChoiceParam("speed", "Speed")
    entries = [ ("Slow", ""),
    ("Normal", ""),
    ("Fast", "")]
    param.setOptions(entries)
    del entries
    param.setDefaultValue("Normal")
    param.restoreDefaultValue()

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(False)
    param.setAnimationEnabled(True)
    lastNode.speed = param
    del param

    param = lastNode.createButtonParam("link", "Link To Parent")

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(False)
    param.setEvaluateOnChange(False)
    lastNode.link = param
    del param

    param = lastNode.createButtonParam("refresh", "Refresh")

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(False)
    param.setEvaluateOnChange(False)
    lastNode.refresh = param
    del param

    param = lastNode.createSeparatorParam("sep5", "")

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setPersistent(False)
    param.setEvaluateOnChange(False)
    lastNode.sep5 = param
    del param

    param = lastNode.createStringParam("time_label", "")
    param.setType(NatronEngine.StringParam.TypeEnum.eStringTypeLabel)
    param.setDefaultValue("- - - - - - - >    TIME :")
    param.restoreDefaultValue()

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setEvaluateOnChange(False)
    param.setAnimationEnabled(False)
    lastNode.time_label = param
    del param

    param = lastNode.createIntParam("start_frame", "Start Frame")
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(100, 0)
    param.setDefaultValue(0, 0)
    param.restoreDefaultValue(0)

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.start_frame = param
    del param

    param = lastNode.createInt3DParam("durations", "Durations")
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(100, 0)
    param.setDefaultValue(0, 0)
    param.restoreDefaultValue(0)
    param.setDisplayMinimum(0, 1)
    param.setDisplayMaximum(100, 1)
    param.setDefaultValue(0, 1)
    param.restoreDefaultValue(1)
    param.setDisplayMinimum(0, 2)
    param.setDisplayMaximum(100, 2)
    param.setDefaultValue(0, 2)
    param.restoreDefaultValue(2)

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(False)
    param.setAnimationEnabled(True)
    param.setValue(150, 0)
    param.setValue(100, 1)
    param.setValue(50, 2)
    lastNode.durations = param
    del param

    param = lastNode.createDoubleParam("transition", "Transition %")
    param.setMinimum(0, 0)
    param.setMaximum(100, 0)
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(100, 0)

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("Es la duracion en que la palabra se armara,\neste es el porcentaje de la duracion de arriba.")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    param.setValue(50, 0)
    lastNode.transition = param
    del param

    param = lastNode.createSeparatorParam("sep6", "")

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setPersistent(False)
    param.setEvaluateOnChange(False)
    lastNode.sep6 = param
    del param

    param = lastNode.createStringParam("texts_label", "")
    param.setType(NatronEngine.StringParam.TypeEnum.eStringTypeLabel)
    param.setDefaultValue("- - - - - - - >    TEXT :")
    param.restoreDefaultValue()

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setEvaluateOnChange(False)
    param.setAnimationEnabled(False)
    lastNode.texts_label = param
    del param

    param = lastNode.createStringParam("title", "Title")
    param.setType(NatronEngine.StringParam.TypeEnum.eStringTypeDefault)

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    param.setValue("casa")
    lastNode.title = param
    del param

    param = lastNode.createStringParam("subtitle", "Subtitle")
    param.setType(NatronEngine.StringParam.TypeEnum.eStringTypeDefault)

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    param.setValue("tocornal")
    lastNode.subtitle = param
    del param

    param = lastNode.createFileParam("font", "Font")
    param.setSequenceEnabled(False)

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(False)
    lastNode.font = param
    del param

    param = lastNode.createColorParam("color", "Color", False)
    param.setMinimum(-2147483648, 0)
    param.setMaximum(2147483647, 0)
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(1, 0)
    param.setMinimum(-2147483648, 1)
    param.setMaximum(2147483647, 1)
    param.setDisplayMinimum(0, 1)
    param.setDisplayMaximum(1, 1)
    param.setMinimum(-2147483648, 2)
    param.setMaximum(2147483647, 2)
    param.setDisplayMinimum(0, 2)
    param.setDisplayMaximum(1, 2)

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    param.setValue(1, 0)
    param.setValue(1, 1)
    param.setValue(1, 2)
    lastNode.color = param
    del param

    param = lastNode.createBooleanParam("separated_by_letter", "Separated by Letter")

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(False)
    param.setAnimationEnabled(True)
    param.setValue(True)
    lastNode.separated_by_letter = param
    del param

    param = lastNode.createButtonParam("text_generator", "Text Generator")

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(False)
    param.setEvaluateOnChange(False)
    lastNode.text_generator = param
    del param

    param = lastNode.createButtonParam("clear_text", "Clear")

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(False)
    param.setEvaluateOnChange(False)
    lastNode.clear_text = param
    del param

    param = lastNode.createSeparatorParam("sep7", "")

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setPersistent(False)
    param.setEvaluateOnChange(False)
    lastNode.sep7 = param
    del param

    param = lastNode.createStringParam("settings_label", "")
    param.setType(NatronEngine.StringParam.TypeEnum.eStringTypeLabel)
    param.setDefaultValue("- - - - - - - >    SETTINGS :")
    param.restoreDefaultValue()

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setEvaluateOnChange(False)
    param.setAnimationEnabled(False)
    lastNode.settings_label = param
    del param

    param = lastNode.createDoubleParam("word_gap", "Word Gap %")
    param.setMinimum(0, 0)
    param.setMaximum(2147483647, 0)
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(100, 0)

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    param.setValue(29.3, 0)
    lastNode.word_gap = param
    del param

    param = lastNode.createDoubleParam("letter_gap", "Letter Gap %")
    param.setMinimum(0, 0)
    param.setMaximum(2147483647, 0)
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(100, 0)

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(False)
    param.setAnimationEnabled(True)
    param.setValue(23.3, 0)
    lastNode.letter_gap = param
    del param

    param = lastNode.createDoubleParam("displacement", "Displacement")
    param.setMinimum(0, 0)
    param.setMaximum(2147483647, 0)
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(2000, 0)

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    param.setValue(500, 0)
    lastNode.displacement = param
    del param

    param = lastNode.createDoubleParam("displacement_angle", "Angle")
    param.setMinimum(-2147483648, 0)
    param.setMaximum(2147483647, 0)
    param.setDisplayMinimum(-180, 0)
    param.setDisplayMaximum(180, 0)

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(False)
    param.setAnimationEnabled(True)
    lastNode.displacement_angle = param
    del param

    param = lastNode.createSeparatorParam("sep8", "")

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setPersistent(False)
    param.setEvaluateOnChange(False)
    lastNode.sep8 = param
    del param

    param = lastNode.createDoubleParam("scale", "Scale")
    param.setMinimum(0, 0)
    param.setMaximum(2147483647, 0)
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(10, 0)

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    param.setValue(2, 0)
    lastNode.scale = param
    del param

    param = lastNode.createDoubleParam("rotate", "Rotate")
    param.setMinimum(-2147483648, 0)
    param.setMaximum(2147483647, 0)
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(360, 0)

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(False)
    param.setAnimationEnabled(True)
    lastNode.rotate = param
    del param

    param = lastNode.createDoubleParam("opacity", "Opacity")
    param.setMinimum(0, 0)
    param.setMaximum(1, 0)
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(1, 0)

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.opacity = param
    del param

    param = lastNode.createSeparatorParam("sep9", "")

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setPersistent(False)
    param.setEvaluateOnChange(False)
    lastNode.sep9 = param
    del param

    param = lastNode.createDoubleParam("blur_x", "Blur X")
    param.setMinimum(0, 0)
    param.setMaximum(2147483647, 0)
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(100, 0)

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    param.setValue(50, 0)
    lastNode.blur_x = param
    del param

    param = lastNode.createDoubleParam("blur_y", "Blur Y")
    param.setMinimum(0, 0)
    param.setMaximum(2147483647, 0)
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(100, 0)

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(False)
    param.setAnimationEnabled(True)
    param.setValue(50, 0)
    lastNode.blur_y = param
    del param

    param = lastNode.createSeparatorParam("sep10", "")

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setPersistent(False)
    param.setEvaluateOnChange(False)
    lastNode.sep10 = param
    del param

    param = lastNode.createBooleanParam("input_transition", "Input Transition")

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    param.setValue(True)
    lastNode.input_transition = param
    del param

    param = lastNode.createBooleanParam("output_transition", "Output Transition")

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(False)
    param.setAnimationEnabled(True)
    lastNode.output_transition = param
    del param

    param = lastNode.createChoiceParam("word_gap_word", "Word Gap")
    entries = [ ("Title", ""),
    ("Subtitle", "")]
    param.setOptions(entries)
    del entries

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("Es la palabra que se va a desfasar.")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.word_gap_word = param
    del param

    param = lastNode.createChoiceParam("letter_gap_direction", "Letter Gap Direction")
    entries = [ ("Left to Right", ""),
    ("Right to Left", "")]
    param.setOptions(entries)
    del entries

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(False)
    param.setAnimationEnabled(True)
    lastNode.letter_gap_direction = param
    del param

    param = lastNode.createButtonParam("texts_refresh", "Texts Refresh")

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(False)
    param.setEvaluateOnChange(False)
    lastNode.texts_refresh = param
    del param

    lastNode.exp = lastNode.createPageParam("exp", "Exp")
    param = lastNode.createInt2DParam("current_format", "Current Format")
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(100, 0)
    param.setDefaultValue(0, 0)
    param.restoreDefaultValue(0)
    param.setDisplayMinimum(0, 1)
    param.setDisplayMaximum(100, 1)
    param.setDefaultValue(0, 1)
    param.restoreDefaultValue(1)

    # Add the param to the page
    lastNode.exp.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    param.setValue(1920, 0)
    param.setValue(1080, 1)
    lastNode.current_format = param
    del param

    param = lastNode.createIntParam("duration", "Current Duration")
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(100, 0)
    param.setDefaultValue(0, 0)
    param.restoreDefaultValue(0)

    # Add the param to the page
    lastNode.exp.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    param.setValue(100, 0)
    lastNode.duration = param
    del param

    param = lastNode.createDoubleParam("rscale", "Rscale")
    param.setMinimum(-2147483648, 0)
    param.setMaximum(2147483647, 0)
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(100, 0)

    # Add the param to the page
    lastNode.exp.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    param.setValue(1, 0)
    lastNode.rscale = param
    del param

    # Refresh the GUI with the newly created parameters
    lastNode.setPagesOrder(['control', 'exp', 'Node', 'Settings'])
    lastNode.refreshUserParamsGUI()
    del lastNode

    # Start of node "Output1"
    lastNode = app.createNode("fr.inria.built-in.Output", 1, group)
    lastNode.setLabel("Output")
    lastNode.setPosition(-126, 1542)
    lastNode.setSize(100, 29)
    lastNode.setColor(0.7, 0.7, 0.7)
    groupOutput1 = lastNode

    del lastNode
    # End of node "Output1"

    # Start of node "Full_HD_Transform"
    lastNode = app.createNode("fr.inria.built-in.Input", 1, group)
    lastNode.setScriptName("Full_HD_Transform")
    lastNode.setLabel("Full HD Transform")
    lastNode.setPosition(-723, 845)
    lastNode.setSize(100, 55)
    lastNode.setColor(0.3, 0.5, 0.2)
    groupFull_HD_Transform = lastNode

    del lastNode
    # End of node "Full_HD_Transform"

    # Start of node "letter_transform_title"
    lastNode = app.createNode("net.sf.openfx.TransformPlugin", 1, group)
    lastNode.setScriptName("letter_transform_title")
    lastNode.setLabel("letter_transform_title")
    lastNode.setPosition(470, 501)
    lastNode.setSize(100, 29)
    lastNode.setColor(0.7, 0.3, 0.1)
    groupletter_transform_title = lastNode

    param = lastNode.getParam("translate")
    if param is not None:
        param.setValue(501.2215656483262, 0)
        param.setValue(496.6597506065243, 1)
        del param

    param = lastNode.getParam("rotate")
    if param is not None:
        param.setValue(24.44614103717126, 0)
        del param

    param = lastNode.getParam("center")
    if param is not None:
        param.setValue(266.7784343516738, 0)
        param.setValue(10.34024939347574, 1)
        del param

    param = lastNode.getParam("transformCenterChanged")
    if param is not None:
        param.setValue(True)
        del param

    param = lastNode.getParam("interactive")
    if param is not None:
        param.setValue(False)
        del param

    param = lastNode.getParam("filter")
    if param is not None:
        param.set("bilinear")
        del param

    param = lastNode.getParam("shutter")
    if param is not None:
        param.setValue(0, 0)
        del param

    del lastNode
    # End of node "letter_transform_title"

    # Start of node "letter_transform_subtitle"
    lastNode = app.createNode("net.sf.openfx.TransformPlugin", 1, group)
    lastNode.setScriptName("letter_transform_subtitle")
    lastNode.setLabel("letter_transform_subtitle")
    lastNode.setPosition(172, 287)
    lastNode.setSize(100, 55)
    lastNode.setColor(0.7, 0.3, 0.1)
    groupletter_transform_subtitle = lastNode

    param = lastNode.getParam("translate")
    if param is not None:
        param.setValue(271.668029113165, 0)
        param.setValue(236.6024783606097, 1)
        del param

    param = lastNode.getParam("rotate")
    if param is not None:
        param.setValue(24.44614103717126, 0)
        del param

    param = lastNode.getParam("center")
    if param is not None:
        param.setValue(496.331970886835, 0)
        param.setValue(270.3975216393903, 1)
        del param

    param = lastNode.getParam("transformCenterChanged")
    if param is not None:
        param.setValue(True)
        del param

    del lastNode
    # End of node "letter_transform_subtitle"

    # Start of node "Merge2"
    lastNode = app.createNode("net.sf.openfx.MergePlugin", 1, group)
    lastNode.setScriptName("Merge2")
    lastNode.setLabel("Merge2")
    lastNode.setPosition(172, 493)
    lastNode.setSize(100, 45)
    lastNode.setColor(0.3, 0.37, 0.776)
    groupMerge2 = lastNode

    param = lastNode.getParam("userTextArea")
    if param is not None:
        param.setValue("<Natron>(over)</Natron>")
        del param

    del lastNode
    # End of node "Merge2"

    # Start of node "general_transform"
    lastNode = app.createNode("net.sf.openfx.TransformPlugin", 1, group)
    lastNode.setScriptName("general_transform")
    lastNode.setLabel("general_transform")
    lastNode.setPosition(-222, 728)
    lastNode.setSize(100, 55)
    lastNode.setColor(0.7, 0.3, 0.1)
    groupgeneral_transform = lastNode

    param = lastNode.getParam("translate")
    if param is not None:
        param.setValue(-192, 0)
        param.setValue(-33, 1)
        del param

    param = lastNode.getParam("rotate")
    if param is not None:
        param.setValue(24.44614103717126, 0)
        del param

    param = lastNode.getParam("scale")
    if param is not None:
        param.setValue(0.5170124696737864, 0)
        param.setValue(0.5170124696737864, 1)
        del param

    param = lastNode.getParam("transformCenterChanged")
    if param is not None:
        param.setValue(True)
        del param

    del lastNode
    # End of node "general_transform"

    # Start of node "Reformat1"
    lastNode = app.createNode("net.sf.openfx.Reformat", 1, group)
    lastNode.setScriptName("Reformat1")
    lastNode.setLabel("Reformat1")
    lastNode.setPosition(-55, 922)
    lastNode.setSize(100, 32)
    lastNode.setColor(0.7, 0.3, 0.1)
    groupReformat1 = lastNode

    param = lastNode.getParam("reformatType")
    if param is not None:
        param.set("box")
        del param

    param = lastNode.getParam("NatronParamFormatChoice")
    if param is not None:
        param.set("PC_Video")
        del param

    param = lastNode.getParam("boxSize")
    if param is not None:
        param.setValue(1920, 0)
        param.setValue(1080, 1)
        del param

    del lastNode
    # End of node "Reformat1"

    # Start of node "Merge4"
    lastNode = app.createNode("net.sf.openfx.MergePlugin", 1, group)
    lastNode.setScriptName("Merge4")
    lastNode.setLabel("Merge4")
    lastNode.setPosition(172, 916)
    lastNode.setSize(100, 45)
    lastNode.setColor(0.3, 0.37, 0.776)
    groupMerge4 = lastNode

    param = lastNode.getParam("userTextArea")
    if param is not None:
        param.setValue("<Natron>(over)</Natron>")
        del param

    del lastNode
    # End of node "Merge4"

    # Start of node "FrameRange"
    lastNode = app.createNode("net.sf.openfx.FrameRange", 1, group)
    lastNode.setScriptName("FrameRange")
    lastNode.setLabel("FrameRange")
    lastNode.setPosition(172, 1066)
    lastNode.setSize(100, 45)
    lastNode.setColor(0.7, 0.65, 0.35)
    groupFrameRange = lastNode

    param = lastNode.getParam("frameRange")
    if param is not None:
        param.setValue(0, 0)
        param.setValue(100, 1)
        del param

    param = lastNode.getParam("userTextArea")
    if param is not None:
        param.setValue("<Natron>(1 - 1)</Natron>")
        del param

    del lastNode
    # End of node "FrameRange"

    # Start of node "time_reverse"
    lastNode = app.createNode("net.sf.openfx.Retime", 1, group)
    lastNode.setScriptName("time_reverse")
    lastNode.setLabel("time_reverse")
    lastNode.setPosition(501, 1074)
    lastNode.setSize(100, 29)
    lastNode.setColor(0.7, 0.65, 0.35)
    grouptime_reverse = lastNode

    param = lastNode.getParam("reverseInput")
    if param is not None:
        param.setValue(True)
        del param

    param = lastNode.getParam("warp")
    if param is not None:
        param.setCurveColor(0, 0.5, 0.5, 1)
        param.deleteAllControlPoints(0)
        param.addControlPoint(0, 0, 0, 1, 1, NatronEngine.Natron.KeyframeTypeEnum.eKeyframeTypeCubic)
        param.addControlPoint(0, 1, 1, 1, 1, NatronEngine.Natron.KeyframeTypeEnum.eKeyframeTypeCubic)
        del param

    param = lastNode.getParam("filter")
    if param is not None:
        param.set("none")
        del param

    del lastNode
    # End of node "time_reverse"

    # Start of node "switch_time_reverse"
    lastNode = app.createNode("net.sf.openfx.switchPlugin", 1, group)
    lastNode.setScriptName("switch_time_reverse")
    lastNode.setLabel("switch_time_reverse")
    lastNode.setPosition(170, 1215)
    lastNode.setSize(100, 29)
    lastNode.setColor(0.3, 0.37, 0.776)
    groupswitch_time_reverse = lastNode

    param = lastNode.getParam("which")
    if param is not None:
        param.setValueAtTime(0, 50, 0)
        param.setValueAtTime(1, 51, 0)
        del param

    del lastNode
    # End of node "switch_time_reverse"

    # Start of node "crop_time_reverse"
    lastNode = app.createNode("net.sf.openfx.CropPlugin", 1, group)
    lastNode.setScriptName("crop_time_reverse")
    lastNode.setLabel("crop_time_reverse")
    lastNode.setPosition(501, 1215)
    lastNode.setSize(100, 29)
    lastNode.setColor(0.7, 0.3, 0.1)
    groupcrop_time_reverse = lastNode

    param = lastNode.getParam("NatronParamFormatChoice")
    if param is not None:
        param.set("PC_Video")
        del param

    param = lastNode.getParam("NatronParamFormatSize")
    if param is not None:
        param.setValue(1920, 0)
        param.setValue(1080, 1)
        del param

    param = lastNode.getParam("bottomLeft")
    if param is not None:
        param.setValueAtTime(238.2870332804825, 50, 0)
        param.setValueAtTime(238.2870332804825, 51, 0)
        param.setValueAtTime(238.2870332804825, 52, 0)
        param.setValueAtTime(238.2870332804825, 53, 0)
        param.setValueAtTime(238.2870332804825, 54, 0)
        param.setValueAtTime(238.3129636349337, 55, 0)
        param.setValueAtTime(238.5303249064833, 56, 0)
        param.setValueAtTime(239.0283565597697, 57, 0)
        param.setValueAtTime(234.5822605751152, 58, 0)
        param.setValueAtTime(235.2660235441974, 59, 0)
        param.setValueAtTime(237.6893391926757, 60, 0)
        param.setValueAtTime(240.1369706806856, 61, 0)
        param.setValueAtTime(242.2202275933286, 62, 0)
        param.setValueAtTime(246.2928992559222, 63, 0)
        param.setValueAtTime(250.6596457839831, 64, 0)
        param.setValueAtTime(256.7510568477652, 65, 0)
        param.setValueAtTime(264.467052540415, 66, 0)
        param.setValueAtTime(275.648791571683, 67, 0)
        param.setValueAtTime(290.0941324586453, 68, 0)
        param.setValueAtTime(308.1510355094929, 69, 0)
        param.setValueAtTime(332.6965757098749, 70, 0)
        param.setValueAtTime(333.6631048561875, 71, 0)
        param.setValueAtTime(325.7888052626114, 72, 0)
        param.setValueAtTime(317.0437077808215, 73, 0)
        param.setValueAtTime(312.5559468683375, 74, 0)
        param.setValueAtTime(310.5822971934336, 75, 0)
        param.setValueAtTime(313.5506211656364, 76, 0)
        param.setValueAtTime(323.030171939932, 77, 0)
        param.setValueAtTime(339.9556135242876, 78, 0)
        param.setValueAtTime(366.408829689256, 79, 0)
        param.setValueAtTime(403.4464429742562, 80, 0)
        param.setValueAtTime(402.9866395692238, 81, 0)
        param.setValueAtTime(403.7429044244878, 82, 0)
        param.setValueAtTime(402.4358591439901, 83, 0)
        param.setValueAtTime(379.8860009211413, 84, 0)
        param.setValueAtTime(367.549165441364, 85, 0)
        param.setValueAtTime(367.0145028150257, 86, 0)
        param.setValueAtTime(382.7157044687797, 87, 0)
        param.setValueAtTime(414.8507836875036, 88, 0)
        param.setValueAtTime(466.034151812699, 89, 0)
        param.setValueAtTime(477.2908376497417, 90, 0)
        param.setValueAtTime(460.4337236953467, 91, 0)
        param.setValueAtTime(429.9889604203452, 92, 0)
        param.setValueAtTime(395.2884374500147, 93, 0)
        param.setValueAtTime(477.9583380607816, 94, 0)
        param.setValueAtTime(514.0264033510605, 95, 0)
        param.setValueAtTime(567.6227766241659, 96, 0)
        param.setValueAtTime(623.4483879372624, 97, 0)
        param.setValueAtTime(580.1972490640588, 98, 0)
        param.setValueAtTime(549.5111329959529, 99, 0)
        param.setValueAtTime(259.9252129723475, 50, 1)
        param.setValueAtTime(259.8852644382758, 51, 1)
        param.setValueAtTime(259.7472506268023, 52, 1)
        param.setValueAtTime(258.6571315356425, 53, 1)
        param.setValueAtTime(258.2873487573608, 54, 1)
        param.setValueAtTime(257.6915167659013, 55, 1)
        param.setValueAtTime(256.9466972159766, 56, 1)
        param.setValueAtTime(256.1794677428543, 57, 1)
        param.setValueAtTime(250.2878022650969, 58, 1)
        param.setValueAtTime(249.0225565123775, 59, 1)
        param.setValueAtTime(248.7171993760178, 60, 1)
        param.setValueAtTime(247.3179415097954, 61, 1)
        param.setValueAtTime(246.0013074335108, 62, 1)
        param.setValueAtTime(245.334576575085, 63, 1)
        param.setValueAtTime(244.0199597013868, 64, 1)
        param.setValueAtTime(244.6253919403956, 65, 1)
        param.setValueAtTime(245.3118079593666, 66, 1)
        param.setValueAtTime(245.3167248400878, 67, 1)
        param.setValueAtTime(247.0765638862285, 68, 1)
        param.setValueAtTime(251.5287081343456, 69, 1)
        param.setValueAtTime(258.1962773748509, 70, 1)
        param.setValueAtTime(250.1888147293274, 71, 1)
        param.setValueAtTime(235.3574325659912, 72, 1)
        param.setValueAtTime(220.1958335448812, 73, 1)
        param.setValueAtTime(209.2555602577362, 74, 1)
        param.setValueAtTime(202.4838619078038, 75, 1)
        param.setValueAtTime(201.8591607705972, 76, 1)
        param.setValueAtTime(206.2342145142887, 77, 1)
        param.setValueAtTime(211.8922126559619, 78, 1)
        param.setValueAtTime(226.5196262243386, 79, 1)
        param.setValueAtTime(253.0310256184732, 80, 1)
        param.setValueAtTime(290.4184363107595, 81, 1)
        param.setValueAtTime(271.5924291857389, 82, 1)
        param.setValueAtTime(244.9746940963682, 83, 1)
        param.setValueAtTime(226.3882409110137, 84, 1)
        param.setValueAtTime(218.3630950834496, 85, 1)
        param.setValueAtTime(215.8455280364803, 86, 1)
        param.setValueAtTime(217.7764567241051, 87, 1)
        param.setValueAtTime(234.9548107311022, 88, 1)
        param.setValueAtTime(288.5310400736437, 89, 1)
        param.setValueAtTime(350.3381863554154, 90, 1)
        param.setValueAtTime(353.9985629460441, 91, 1)
        param.setValueAtTime(323.1784921193387, 92, 1)
        param.setValueAtTime(311.0239895475895, 93, 1)
        param.setValueAtTime(533.8867384216734, 94, 1)
        param.setValueAtTime(545.3703234072207, 95, 1)
        param.setValueAtTime(597.9014839749839, 96, 1)
        param.setValueAtTime(661.675882572981, 97, 1)
        param.setValueAtTime(643.5160758561765, 98, 1)
        param.setValueAtTime(654.4053737379168, 99, 1)
        del param

    param = lastNode.getParam("size")
    if param is not None:
        param.setValueAtTime(1123.957437124015, 50, 0)
        param.setValueAtTime(1123.957437124015, 51, 0)
        param.setValueAtTime(1123.957437124015, 52, 0)
        param.setValueAtTime(1123.957437124015, 53, 0)
        param.setValueAtTime(1123.957437124015, 54, 0)
        param.setValueAtTime(1125.36109549548, 55, 0)
        param.setValueAtTime(1130.447753678689, 56, 0)
        param.setValueAtTime(1136.284805470273, 57, 0)
        param.setValueAtTime(1151.1849615356, 58, 0)
        param.setValueAtTime(1160.654490128342, 59, 0)
        param.setValueAtTime(1170.612087767988, 60, 0)
        param.setValueAtTime(1183.429185283331, 61, 0)
        param.setValueAtTime(1197.695570241569, 62, 0)
        param.setValueAtTime(1211.214139165078, 63, 0)
        param.setValueAtTime(1227.677370228804, 64, 0)
        param.setValueAtTime(1241.016359422482, 65, 0)
        param.setValueAtTime(1260.771903712504, 66, 0)
        param.setValueAtTime(1300.411882472331, 67, 0)
        param.setValueAtTime(1339.62259346754, 68, 0)
        param.setValueAtTime(1376.497077254975, 69, 0)
        param.setValueAtTime(1405.882505946312, 70, 0)
        param.setValueAtTime(1455.102837672056, 71, 0)
        param.setValueAtTime(1511.193266425151, 72, 0)
        param.setValueAtTime(1561.312283732246, 73, 0)
        param.setValueAtTime(1601.266419143787, 74, 0)
        param.setValueAtTime(1629.811290855497, 75, 0)
        param.setValueAtTime(1644.94106985025, 76, 0)
        param.setValueAtTime(1663.135729876966, 77, 0)
        param.setValueAtTime(1719.911149241728, 78, 0)
        param.setValueAtTime(1761.964826419948, 79, 0)
        param.setValueAtTime(1782.612113572057, 80, 0)
        param.setValueAtTime(1831.016243537299, 81, 0)
        param.setValueAtTime(1863.93823238264, 82, 0)
        param.setValueAtTime(1886.251508148886, 83, 0)
        param.setValueAtTime(1913.888876311355, 84, 0)
        param.setValueAtTime(1917.994740964371, 85, 0)
        param.setValueAtTime(1942.397739962166, 86, 0)
        param.setValueAtTime(2011.391464169229, 87, 0)
        param.setValueAtTime(2054.874877808617, 88, 0)
        param.setValueAtTime(1943.307851244649, 89, 0)
        param.setValueAtTime(1843.42518128438, 90, 0)
        param.setValueAtTime(1861.714650294181, 91, 0)
        param.setValueAtTime(1877.078107805387, 92, 0)
        param.setValueAtTime(1956.931219275314, 93, 0)
        param.setValueAtTime(1960.259808364138, 94, 0)
        param.setValueAtTime(2000.2483049495, 95, 0)
        param.setValueAtTime(1841.421418133228, 96, 0)
        param.setValueAtTime(1616.788703656823, 97, 0)
        param.setValueAtTime(1491.630835291694, 98, 0)
        param.setValueAtTime(1219.156389368938, 99, 0)
        param.setValueAtTime(706.2213497154792, 50, 1)
        param.setValueAtTime(706.2612982495508, 51, 1)
        param.setValueAtTime(706.3993120610244, 52, 1)
        param.setValueAtTime(707.4894311521841, 53, 1)
        param.setValueAtTime(707.8592139304658, 54, 1)
        param.setValueAtTime(708.4550459219254, 55, 1)
        param.setValueAtTime(709.19986547185, 56, 1)
        param.setValueAtTime(709.9670949449724, 57, 1)
        param.setValueAtTime(715.8587604227298, 58, 1)
        param.setValueAtTime(717.1240061754492, 59, 1)
        param.setValueAtTime(717.4293633118089, 60, 1)
        param.setValueAtTime(718.8286211780312, 61, 1)
        param.setValueAtTime(720.2321943777947, 62, 1)
        param.setValueAtTime(721.4059828026265, 63, 1)
        param.setValueAtTime(723.7959738886868, 64, 1)
        param.setValueAtTime(730.9319484582679, 65, 1)
        param.setValueAtTime(734.8066185641571, 66, 1)
        param.setValueAtTime(743.5188060900025, 67, 1)
        param.setValueAtTime(751.0863778624695, 68, 1)
        param.setValueAtTime(757.6908334511834, 69, 1)
        param.setValueAtTime(762.4921882252888, 70, 1)
        param.setValueAtTime(781.9226434773003, 71, 1)
        param.setValueAtTime(808.6156540808538, 72, 1)
        param.setValueAtTime(843.6560468025923, 73, 1)
        param.setValueAtTime(894.2612847709847, 74, 1)
        param.setValueAtTime(940.9354657732257, 75, 1)
        param.setValueAtTime(982.0199585166391, 76, 1)
        param.setValueAtTime(1017.627531111364, 77, 1)
        param.setValueAtTime(1054.861843084889, 78, 1)
        param.setValueAtTime(1080.649525893264, 79, 1)
        param.setValueAtTime(1107.384903751605, 80, 1)
        param.setValueAtTime(1116.013071306873, 81, 1)
        param.setValueAtTime(1178.678866299629, 82, 1)
        param.setValueAtTime(1237.136767826909, 83, 1)
        param.setValueAtTime(1274.098586323129, 84, 1)
        param.setValueAtTime(1314.483909405667, 85, 1)
        param.setValueAtTime(1383.813411977068, 86, 1)
        param.setValueAtTime(1439.312481954886, 87, 1)
        param.setValueAtTime(1467.84739501908, 88, 1)
        param.setValueAtTime(1457.847590940966, 89, 1)
        param.setValueAtTime(1424.754958823422, 90, 1)
        param.setValueAtTime(1431.46571836435, 91, 1)
        param.setValueAtTime(1455.574394449679, 92, 1)
        param.setValueAtTime(1505.708651185298, 93, 1)
        param.setValueAtTime(1350.350288696687, 94, 1)
        param.setValueAtTime(1390.623499918545, 95, 1)
        param.setValueAtTime(1329.335098189503, 96, 1)
        param.setValueAtTime(1226.526592690956, 97, 1)
        param.setValueAtTime(1274.713151704909, 98, 1)
        param.setValueAtTime(1191.841097662673, 99, 1)
        del param

    param = lastNode.getParam("blackOutside")
    if param is not None:
        param.setValue(True)
        del param

    del lastNode
    # End of node "crop_time_reverse"

    # Start of node "in_out_switch"
    lastNode = app.createNode("net.sf.openfx.switchPlugin", 1, group)
    lastNode.setScriptName("in_out_switch")
    lastNode.setLabel("in_out_switch")
    lastNode.setPosition(-126, 1437)
    lastNode.setSize(100, 29)
    lastNode.setColor(0.3, 0.37, 0.776)
    groupin_out_switch = lastNode

    del lastNode
    # End of node "in_out_switch"

    # Start of node "Dot1"
    lastNode = app.createNode("fr.inria.built-in.Dot", 1, group)
    lastNode.setScriptName("Dot1")
    lastNode.setLabel("Dot1")
    lastNode.setPosition(-83, 1081)
    lastNode.setSize(14, 14)
    lastNode.setColor(0.7, 0.7, 0.7)
    groupDot1 = lastNode

    del lastNode
    # End of node "Dot1"

    # Start of node "Dot3"
    lastNode = app.createNode("fr.inria.built-in.Dot", 1, group)
    lastNode.setScriptName("Dot3")
    lastNode.setLabel("Dot3")
    lastNode.setPosition(544, 1446)
    lastNode.setSize(14, 14)
    lastNode.setColor(0.7, 0.7, 0.7)
    groupDot3 = lastNode

    del lastNode
    # End of node "Dot3"

    # Start of node "TextFit"
    lastNode = app.createNode("vv.TextFit", 1, group)
    lastNode.setScriptName("TextFit")
    lastNode.setLabel("TextFit")
    lastNode.setPosition(-385, 916)
    lastNode.setSize(100, 32)
    lastNode.setColor(0.7, 0.7, 0.7)
    groupTextFit = lastNode

    param = lastNode.getParam("onParamChanged")
    if param is not None:
        param.setValue("text_fit.main")
        del param


    # Create the user parameters
    lastNode.control = lastNode.createPageParam("control", "Control")
    param = lastNode.createStringParam("state_label", "State")
    param.setType(NatronEngine.StringParam.TypeEnum.eStringTypeLabel)
    param.setDefaultValue("- - - - - - - >    STATE :")
    param.restoreDefaultValue()

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setEvaluateOnChange(False)
    param.setAnimationEnabled(False)
    param.setValue("- - - - - - - >    STATE :")
    lastNode.state_label = param
    del param

    param = lastNode.createChoiceParam("format", "Format")
    entries = [ ("Quarter HD - 480 x 270", ""),
    ("Half HD - 960 x 540", ""),
    ("Full HD - 1920 x 1080", ""),
    ("4K - 3840 x 2160", "")]
    param.setOptions(entries)
    del entries
    param.setDefaultValue("Full HD - 1920 x 1080")
    param.restoreDefaultValue()

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    param.set("Full HD - 1920 x 1080")
    lastNode.format = param
    del param

    param = lastNode.createButtonParam("link", "Link To Parent")

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(False)
    param.setEvaluateOnChange(False)
    lastNode.link = param
    del param

    param = lastNode.createButtonParam("refresh", "Refresh")

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(False)
    param.setEvaluateOnChange(False)
    lastNode.refresh = param
    del param

    param = lastNode.createSeparatorParam("sep5", "")

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setPersistent(False)
    param.setEvaluateOnChange(False)
    lastNode.sep5 = param
    del param

    param = lastNode.createStringParam("texts_label", "")
    param.setType(NatronEngine.StringParam.TypeEnum.eStringTypeLabel)
    param.setDefaultValue("- - - - - - - >    TEXT :")
    param.restoreDefaultValue()

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setEvaluateOnChange(False)
    param.setAnimationEnabled(False)
    param.setValue("- - - - - - - >    TEXT :")
    lastNode.texts_label = param
    del param

    param = lastNode.createStringParam("title", "Title")
    param.setType(NatronEngine.StringParam.TypeEnum.eStringTypeDefault)

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    param.setValue("casa")
    lastNode.title = param
    del param

    param = lastNode.createStringParam("subtitle", "Subtitle")
    param.setType(NatronEngine.StringParam.TypeEnum.eStringTypeDefault)

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    param.setValue("tocornal")
    lastNode.subtitle = param
    del param

    param = lastNode.createFileParam("font", "Font")
    param.setSequenceEnabled(False)

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(False)
    param.setValue("")
    lastNode.font = param
    del param

    param = lastNode.createSeparatorParam("sep7", "")

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setPersistent(False)
    param.setEvaluateOnChange(False)
    lastNode.sep7 = param
    del param

    param = lastNode.createStringParam("settings_label", "")
    param.setType(NatronEngine.StringParam.TypeEnum.eStringTypeLabel)
    param.setDefaultValue("- - - - - - - >    SETTINGS :")
    param.restoreDefaultValue()

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setEvaluateOnChange(False)
    param.setAnimationEnabled(False)
    param.setValue("- - - - - - - >    SETTINGS :")
    lastNode.settings_label = param
    del param

    param = lastNode.createIntParam("font_size_title", "Title Font Size")
    param.setMinimum(0, 0)
    param.setMaximum(2000, 0)
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(1000, 0)
    param.setDefaultValue(0, 0)
    param.restoreDefaultValue(0)

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    param.setValue(387, 0)
    lastNode.font_size_title = param
    del param

    param = lastNode.createInt2DParam("title_position", "Title Position")
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(100, 0)
    param.setDefaultValue(0, 0)
    param.restoreDefaultValue(0)
    param.setDisplayMinimum(0, 1)
    param.setDisplayMaximum(100, 1)
    param.setDefaultValue(0, 1)
    param.restoreDefaultValue(1)

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(False)
    param.setAnimationEnabled(True)
    param.setValue(444, 0)
    param.setValue(520, 1)
    lastNode.title_position = param
    del param

    param = lastNode.createIntParam("font_size_subtitle", "Subtitle Font Size")
    param.setMinimum(0, 0)
    param.setMaximum(2000, 0)
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(1000, 0)
    param.setDefaultValue(0, 0)
    param.restoreDefaultValue(0)

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    param.setValue(360, 0)
    lastNode.font_size_subtitle = param
    del param

    param = lastNode.createInt2DParam("subtitle_position", "Subtitle Position")
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(100, 0)
    param.setDefaultValue(0, 0)
    param.restoreDefaultValue(0)
    param.setDisplayMinimum(0, 1)
    param.setDisplayMaximum(100, 1)
    param.setDefaultValue(0, 1)
    param.restoreDefaultValue(1)

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(False)
    param.setAnimationEnabled(True)
    param.setValue(17, 1)
    lastNode.subtitle_position = param
    del param

    param = lastNode.createButtonParam("separate_text", "Separate Text")

    # Add the param to the page
    lastNode.control.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setEvaluateOnChange(False)
    lastNode.separate_text = param
    del param

    lastNode.exp = lastNode.createPageParam("exp", "Exp")
    param = lastNode.createInt2DParam("current_format", "Current Format")
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(100, 0)
    param.setDefaultValue(0, 0)
    param.restoreDefaultValue(0)
    param.setDisplayMinimum(0, 1)
    param.setDisplayMaximum(100, 1)
    param.setDefaultValue(0, 1)
    param.restoreDefaultValue(1)

    # Add the param to the page
    lastNode.exp.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    param.setValue(1920, 0)
    param.setValue(1080, 1)
    lastNode.current_format = param
    del param

    param = lastNode.createDoubleParam("rscale", "Rscale")
    param.setMinimum(-2147483648, 0)
    param.setMaximum(2147483647, 0)
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(100, 0)

    # Add the param to the page
    lastNode.exp.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    param.setValue(1, 0)
    lastNode.rscale = param
    del param

    # Refresh the GUI with the newly created parameters
    lastNode.setPagesOrder(['control', 'exp', 'Node', 'Settings'])
    lastNode.refreshUserParamsGUI()
    del lastNode
    # End of node "TextFit"

    # Start of node "origina_input_transform"
    lastNode = app.createNode("net.sf.openfx.TransformPlugin", 1, group)
    lastNode.setScriptName("origina_input_transform")
    lastNode.setLabel("origina_input_transform")
    lastNode.setPosition(-385, 731)
    lastNode.setSize(100, 55)
    lastNode.setColor(0.7, 0.3, 0.1)
    grouporigina_input_transform = lastNode

    param = lastNode.getParam("translate")
    if param is not None:
        param.setValue(-192, 0)
        param.setValue(-33, 1)
        del param

    param = lastNode.getParam("rotate")
    if param is not None:
        param.setValue(24.44614103717126, 0)
        del param

    param = lastNode.getParam("scale")
    if param is not None:
        param.setValue(0.5170124696737864, 0)
        param.setValue(0.5170124696737864, 1)
        del param

    param = lastNode.getParam("transformCenterChanged")
    if param is not None:
        param.setValue(True)
        del param

    del lastNode
    # End of node "origina_input_transform"

    # Now that all nodes are created we can connect them together, restore expressions
    groupOutput1.connectInput(0, groupin_out_switch)
    groupMerge2.connectInput(0, groupletter_transform_subtitle)
    groupMerge2.connectInput(1, groupletter_transform_title)
    groupMerge4.connectInput(0, groupReformat1)
    groupMerge4.connectInput(1, groupMerge2)
    groupFrameRange.connectInput(0, groupMerge4)
    grouptime_reverse.connectInput(0, groupFrameRange)
    groupswitch_time_reverse.connectInput(0, groupFrameRange)
    groupswitch_time_reverse.connectInput(1, groupcrop_time_reverse)
    groupcrop_time_reverse.connectInput(0, grouptime_reverse)
    groupin_out_switch.connectInput(0, groupDot1)
    groupin_out_switch.connectInput(1, groupswitch_time_reverse)
    groupin_out_switch.connectInput(2, groupDot3)
    groupDot1.connectInput(0, groupFrameRange)
    groupDot3.connectInput(0, groupcrop_time_reverse)
    groupTextFit.connectInput(0, grouporigina_input_transform)

    param = groupReformat1.getParam("boxSize")
    param.setExpression("thisGroup.current_format.getValue(dimension)", False, 0)
    param.setExpression("thisGroup.current_format.getValue(dimension)", False, 1)
    del param
    param = groupTextFit.getParam("state_label")
    param.setExpression("thisGroup.state_label.get()", False, 0)
    del param
    param = groupTextFit.getParam("format")
    param.setExpression("thisGroup.format.get()", False, 0)
    del param
    param = groupTextFit.getParam("texts_label")
    param.setExpression("thisGroup.texts_label.get()", False, 0)
    del param
    param = groupTextFit.getParam("title")
    param.setExpression("thisGroup.title.get()", False, 0)
    del param
    param = groupTextFit.getParam("subtitle")
    param.setExpression("thisGroup.subtitle.get()", False, 0)
    del param
    param = groupTextFit.getParam("font")
    param.setExpression("thisGroup.font.get()", False, 0)
    del param
    param = groupTextFit.getParam("settings_label")
    param.setExpression("thisGroup.settings_label.get()", False, 0)
    del param
    param = groupTextFit.getParam("current_format")
    param.setExpression("index = thisNode.format.get()\nret = general.formats[index][dimension]", True, 0)
    param.setExpression("index = thisNode.format.get()\nret = general.formats[index][dimension]", True, 1)
    del param
    param = groupTextFit.getParam("rscale")
    param.setExpression("index = thisNode.format.get()\nret = general.rscale[index]", True, 0)
    del param

    param = group.getParam("current_format")
    param.setExpression("index = thisNode.format.get()\nret = general.formats[index][dimension]", True, 0)
    param.setExpression("index = thisNode.format.get()\nret = general.formats[index][dimension]", True, 1)
    del param
    param = group.getParam("duration")
    param.setExpression("index = thisNode.speed.get()\nret = thisNode.durations.get()[index]", True, 0)
    del param
    param = group.getParam("rscale")
    param.setExpression("index = thisNode.format.get()\nret = general.rscale[index]", True, 0)
    del param
    try:
        extModule = sys.modules["LetterAnimationExt"]
    except KeyError:
        extModule = None
    if extModule is not None and hasattr(extModule ,"createInstanceExt") and hasattr(extModule.createInstanceExt,"__call__"):
        extModule.createInstanceExt(app,group)
